disabled_rules:
  - trailing_whitespace
  
opt_in_rules:
  - force_unwrapping
  - empty_count

excluded:
  - Pods
  - DerivedData

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length: 2
  max_length: 50